name: Maatify Library CI

on:
  workflow_call:
    secrets:
      TELEGRAM_CI_BOT_TOKEN:
        required: true
      TELEGRAM_CI_CHAT_ID:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GH_START_ISO: ${{ github.event.head_commit.timestamp }}

    strategy:
      matrix:
        php: [ "8.2", "8.3" ]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer

      - run: composer install --no-interaction --prefer-dist --no-progress

      - name: 🧹 Run PHPStan
        run: composer analyse

      - name: 🧪 Run PHPUnit with Coverage
        run: |
          vendor/bin/phpunit \
            --configuration phpunit.xml.dist \
            --coverage-clover coverage.xml \
            | tee phpunit.log

      - name: Extract Coverage
        id: coverage
        run: |
          COV=$(php -r '
            $x=@simplexml_load_file("coverage.xml");
            if(!$x){echo 0;exit;}
            $m=$x->project->metrics;
            $s=(int)$m["statements"];
            $c=(int)$m["coveredstatements"];
            echo $s>0 ? (int)round(($c/$s)*100) : 0;
          ')
          echo "coverage=$COV" >> $GITHUB_OUTPUT

      - name: 🧾 Summary
        if: always()
        run: |
          echo "### 🧾 Library CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "📦 $GITHUB_REPOSITORY" >> $GITHUB_STEP_SUMMARY
          echo "🐘 PHP ${{ matrix.php }}" >> $GITHUB_STEP_SUMMARY
          echo "📊 Coverage: ${{ steps.coverage.outputs.coverage }}%" >> $GITHUB_STEP_SUMMARY

      - name: 📲 Notify Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CI_CHAT_ID }}
        run: |
          START_TS=$(date -u -d "$GH_START_ISO" +%s)
          END_TS=$(date +%s)
          DURATION=$((END_TS - START_TS))

          if [ $DURATION -lt 60 ]; then
            DURATION_STR="${DURATION}s"
          else
            DURATION_STR="$(($DURATION/60))m $(($DURATION%60))s"
          fi

          STATUS="✅ Passed"
          COLOR="🟢"
          [ "${{ job.status }}" != "success" ] && STATUS="❌ Failed" && COLOR="🔴"

          MESSAGE="📢 <b>Maatify Library CI</b>

          ${COLOR} ${STATUS}

          📦 <b>Repo:</b> ${GITHUB_REPOSITORY}
          🌿 <b>Branch:</b> ${GITHUB_REF_NAME}
          📊 <b>Coverage:</b> ${{ steps.coverage.outputs.coverage }}%
          ⏳ <b>Duration:</b> ${DURATION_STR}

          🔗 <a href='${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'>View Run</a>
          "

          curl -s -X POST \
            "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg chat_id "$TELEGRAM_CHAT_ID" --arg text "$MESSAGE" --arg pm HTML '{chat_id:$chat_id,text:$text,parse_mode:$pm}')"
